---
- name: Ждать доступности порта SSH (22) на всех серверах
  hosts: all
  gather_facts: no
  tasks:
    - name: Ждать доступности порта SSH (22)
      wait_for:
        port: 22
        state: started
        delay: 5
        timeout: 60

- name: Подготовка каталога remote_tmp для Ansible
  hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: Создать каталог /root/.ansible/tmp
      file:
        path: /root/.ansible/tmp
        state: directory
        mode: '0700'

- name: Базовая конфигурация для всех серверов
  hosts: all
  become: yes
  gather_facts: yes
  vars:
    ssh_pub_key: "{{ lookup('file', 'ssh/id_rsa.pub') }}"
  roles:
    - base

- name: Конфигурация сервера A (PostgreSQL)
  hosts: hostA.renue
  become: yes
  vars:
    postgres_version: "12"
    postgres_users:
      - { name: "app", password: "app", db: "app" }
      - { name: "custom", password: "custom", db: "custom" }
      - { name: "service", password: "service" }
  roles:
    - postgres

- name: Конфигурация сервера Б (nginx)
  hosts: hostB.renue
  become: yes
  roles:
    - nginx